logLevel: info
wsEndpoint: "wss://kusama-rpc.polkadot.io/"
targetsFromGit: #optional
  enabled: false
  targets:
  - platform: GitHub1kv
    private:
      enabled: false
      apiToken: xxx
    network: kusama
    url: https://raw.githubusercontent.com/w3f/1k-validators-be/master/candidates/kusama.json
  - platform: GitLab
    private:
      enabled: false
      apiToken: xxx
    network: kusama
    url: https://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main  
matrix: #optional
  enabled: false
  baseUrl: "https://matrix.org"
  password: "xxx"
  userId: "@bot:matrix.org"
  room: "!xxx:matrix.org"
  notifyRestarts: false
targets: #optional  
- alias: validator-000
    validatorAddress: "<validator-000-stash-address>"
- alias: validator-001
  validatorAddress: "<validator-001-stash-address>"
deepCheck:
  enabled: false
claim:
  enabled: false
  batchSize: 2
  gracePeriod:
    enabled: false
    eras: 4
  claimerKeystore:
    filePath: /path/to/validator-000/keystore
    passwordPath: /path/to/validator-000/keystore/password