{{ if eq .Values.config.matrix.enabled true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 
{{ end }}